"use client";

import { useState } from "react";

export type JournalEntryEvidence = { id: string; source_type: string; symbol: string; gross_pnl: string; net_pnl: string; r_multiple?: string; evidence: Record<string, unknown>; closed_at: string; immutable: boolean; annotations?: Array<{ id: string; content: string; supersedes_id?: string; created_at: string }>; attachments?: Array<{ id: string; original_name: string; media_type: string; checksum: string; download_path: string }> };

export function Journal({ entries, selectedIds, busy, onProject, onToggle, onAnnotate, onAttach }: { entries: JournalEntryEvidence[]; selectedIds: string[]; busy: boolean; onProject: () => Promise<void>; onToggle: (id: string) => void; onAnnotate: (id: string, content: string) => Promise<void>; onAttach: (id: string, file: File) => Promise<void> }) {
  const [annotation, setAnnotation] = useState("");
  const [annotationEntry, setAnnotationEntry] = useState("");
  return <section aria-labelledby="journal"><h3 id="journal">Immutable trading journal</h3><p>Completed paper, recommended, and discretionary trades are projected automatically. Notes append new versions rather than editing history.</p><button disabled={busy} onClick={onProject} type="button">{busy ? "Updating…" : "Update from completed activity"}</button>{entries.length ? <div className="journal-entry-list">{entries.map((entry) => <article className="journal-entry" key={entry.id}><header><label className="confirmation-check"><input checked={selectedIds.includes(entry.id)} onChange={() => onToggle(entry.id)} type="checkbox" /><span><strong>{entry.symbol}</strong><small>{entry.source_type} · {new Date(entry.closed_at).toLocaleString()}</small></span></label><button className="secondary-button" onClick={() => setAnnotationEntry(entry.id)} type="button">Annotate</button></header><dl className="evidence-metrics"><div><dt>Gross P/L</dt><dd>{entry.gross_pnl}</dd></div><div><dt>Net P/L</dt><dd>{entry.net_pnl}</dd></div><div><dt>R multiple</dt><dd>{entry.r_multiple ?? "—"}</dd></div></dl><details><summary>Automatic evidence</summary><pre>{JSON.stringify(entry.evidence, null, 2)}</pre></details><details><summary>Annotations ({entry.annotations?.length ?? 0})</summary>{entry.annotations?.length ? <ol className="timeline">{entry.annotations.map((item) => <li key={item.id}><strong>{item.content}</strong><span>{new Date(item.created_at).toLocaleString()}</span><small>{item.supersedes_id ? `Supersedes ${item.supersedes_id}` : "First annotation"}</small></li>)}</ol> : <p>No annotations yet.</p>}</details><details><summary>Protected attachments ({entry.attachments?.length ?? 0})</summary>{entry.attachments?.length ? <ul>{entry.attachments.map((item) => <li key={item.id}><a href={item.download_path}>{item.original_name}</a> <small>{item.media_type} · {item.checksum.slice(0, 12)}…</small></li>)}</ul> : <p>No attachments yet.</p>}</details></article>)}</div> : <p className="workspace-notice">No completed paper or broker trade has been journaled yet.</p>}{annotationEntry ? <div className="setup-form"><label>Behavioral context and review notes<textarea onChange={(event) => setAnnotation(event.target.value)} placeholder="Plan adherence, emotion, entry quality, or review notes" value={annotation} /></label><label>Protected screenshot<input accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={(event) => { const file = event.target.files?.[0]; if (file) void onAttach(annotationEntry, file); }} type="file" /></label><button disabled={busy || !annotation.trim()} onClick={async () => { await onAnnotate(annotationEntry, annotation); setAnnotation(""); setAnnotationEntry(""); }} type="button">Append annotation</button></div> : null}</section>;
}
