"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { api } from "@/lib/api";

export type ModelProfile = { id: string; name: string; runtime: "CODEX_APP_SERVER" | "LITELLM_GATEWAY"; provider: string; model: string; fallback_profile_ids: string[]; capabilities: string[]; active: boolean };
type RuntimeSettings = { codex_enabled: boolean; litellm_enabled: boolean; litellm_url: string; default_codex_model: string; litellm_api_key_configured: boolean; restart_required: boolean };

export function ModelProfiles() {
  const client = useQueryClient();
  const profiles = useQuery<ModelProfile[]>({ queryKey: ["agents", "profiles"], queryFn: () => api("/agents/profiles") });
  const runtimes = useQuery<Array<{ type: string; default: boolean; enabled: boolean; explicit_opt_in?: boolean; url?: string; api_key_configured?: boolean }>>({ queryKey: ["agents", "runtimes"], queryFn: () => api("/agents/runtimes") });
  const settings = useQuery<RuntimeSettings>({ queryKey: ["agents", "runtime-settings"], queryFn: () => api("/agents/runtime-settings") });
  const [runtimeForm, setRuntimeForm] = useState({ codex_enabled: true, litellm_enabled: false, litellm_url: "http://localhost:4000", litellm_api_key: "", default_codex_model: "gpt-5.6-terra" });
  const [formReady, setFormReady] = useState(false);
  const [form, setForm] = useState({ name: "", runtime: "CODEX_APP_SERVER" as ModelProfile["runtime"], provider: "openai", model: "", fallback_profile_ids: [] as string[] });
  const [error, setError] = useState("");
  const saveRuntime = useMutation({ mutationFn: () => api("/agents/runtime-settings", { method: "PUT", body: JSON.stringify(runtimeForm) }), onSuccess: async () => { setRuntimeForm({ ...runtimeForm, litellm_api_key: "" }); setFormReady(true); await client.invalidateQueries({ queryKey: ["agents"] }); }, onError: (e: Error) => setError(e.message) });
  const testRuntime = useMutation({ mutationFn: () => api<{ status: string; message: string }>("/agents/runtime-settings/test", { method: "POST" }), onSuccess: result => setError(`${result.status}: ${result.message}`), onError: (e: Error) => setError(e.message) });
  const save = useMutation({ mutationFn: () => api("/agents/profiles", { method: "POST", body: JSON.stringify({ ...form, capabilities: ["structured_output", "reasoning"], parameters: {}, active: true }) }), onSuccess: async () => { setForm({ ...form, name: "", model: "", fallback_profile_ids: [] }); await client.invalidateQueries({ queryKey: ["agents"] }); }, onError: (e: Error) => setError(e.message) });
  const submit = (event: FormEvent) => { event.preventDefault(); setError(""); save.mutate(); };
  if (settings.data && !formReady) { setRuntimeForm({ codex_enabled: settings.data.codex_enabled, litellm_enabled: settings.data.litellm_enabled, litellm_url: settings.data.litellm_url, litellm_api_key: "", default_codex_model: settings.data.default_codex_model }); setFormReady(true); }
  return <section className="section-stack"><header><p className="eyebrow">Runtime authority</p><h1>Agent runtimes & model profiles</h1><p className="muted">Codex App Server is the default. LiteLLM is an explicit, independently configurable alternative.</p></header>
    <div className="grid two">{runtimes.data?.map(runtime => <article className="card" key={runtime.type}><h2>{runtime.type.replaceAll("_", " ")}</h2><span className={`status ${runtime.enabled ? "healthy" : "disabled"}`}>{runtime.enabled ? "Enabled" : "Disabled"}</span><p>{runtime.default ? "Platform default" : "Explicit opt-in only"} · explicit assignment</p>{runtime.type === "LITELLM_GATEWAY" && <small>{runtime.api_key_configured ? "Encrypted API key configured" : "API key not configured"} · {runtime.url}</small>}</article>)}</div>
    <form className="card form-grid wide" onSubmit={e => { e.preventDefault(); saveRuntime.mutate(); }}><h2 className="full">Platform runtime controls</h2><p className="muted full">Enable LiteLLM here, save, then restart the agent-worker. For Docker, start the optional gateway with <code>docker compose --profile litellm up -d litellm</code>. Use <code>http://litellm:4000</code> from the worker container or <code>http://localhost:4000</code> from a local worker.</p><label><input type="checkbox" checked={runtimeForm.codex_enabled} onChange={e => setRuntimeForm({ ...runtimeForm, codex_enabled: e.target.checked })} /> Codex App Server enabled</label><label><input type="checkbox" checked={runtimeForm.litellm_enabled} onChange={e => setRuntimeForm({ ...runtimeForm, litellm_enabled: e.target.checked })} /> LiteLLM gateway enabled</label><label>LiteLLM URL<input value={runtimeForm.litellm_url} onChange={e => setRuntimeForm({ ...runtimeForm, litellm_url: e.target.value })} /></label><label>LiteLLM API key<input type="password" placeholder={settings.data?.litellm_api_key_configured ? "Leave blank to keep current key" : "Gateway key"} value={runtimeForm.litellm_api_key} onChange={e => setRuntimeForm({ ...runtimeForm, litellm_api_key: e.target.value })} /></label><label>Default Codex model<input required value={runtimeForm.default_codex_model} onChange={e => setRuntimeForm({ ...runtimeForm, default_codex_model: e.target.value })} /></label><div className="actions full"><button className="btn primary" disabled={saveRuntime.isPending}>Save runtime settings</button><button type="button" className="btn" disabled={testRuntime.isPending} onClick={() => testRuntime.mutate()}>Test LiteLLM gateway</button></div>{settings.data?.restart_required && <p className="notice warn full">Runtime settings are persisted encrypted. Restart agent-worker to apply them.</p>}{error && <p className="notice bad full">{error}</p>}</form>
    <form className="card form-grid wide" onSubmit={submit}><h2 className="full">Create immutable model profile</h2><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label>Runtime<select value={form.runtime} onChange={e => setForm({ ...form, runtime: e.target.value as ModelProfile["runtime"] })}><option>CODEX_APP_SERVER</option><option>LITELLM_GATEWAY</option></select></label><label>Provider<input required value={form.provider} onChange={e => setForm({ ...form, provider: e.target.value })} /></label><label>Model<input required placeholder="Configured runtime model" value={form.model} onChange={e => setForm({ ...form, model: e.target.value })} /></label><label className="full">Same-runtime fallback<select multiple value={form.fallback_profile_ids} onChange={e => setForm({ ...form, fallback_profile_ids: Array.from(e.target.selectedOptions).map(option => option.value) })}>{profiles.data?.filter(item => item.runtime === form.runtime).map(item => <option value={item.id} key={item.id}>{item.name} · {item.model}</option>)}</select></label><button className="btn primary" disabled={save.isPending}>Save profile version</button></form>
    <article className="card"><h2>Profile catalog</h2>{profiles.isPending ? <p>Loading…</p> : profiles.data?.length ? <div className="table-wrap"><table><thead><tr><th>Name</th><th>Runtime</th><th>Provider / model</th><th>Fallbacks</th></tr></thead><tbody>{profiles.data.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.runtime}</td><td>{item.provider} / {item.model}</td><td>{item.fallback_profile_ids.length}</td></tr>)}</tbody></table></div> : <p className="empty">No profiles available.</p>}</article></section>;
}
