from tests.contract.test_hil2_contract import test_hil2_write_is_disabled_for_autonomous_execution
from tests.integration.test_position_reconciliation import test_exact_ambiguous_and_no_match


def test_release_hil2_to_autonomous_reconciliation():
    test_hil2_write_is_disabled_for_autonomous_execution()
    test_exact_ambiguous_and_no_match()
