"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { api, type Resource, withStepUp } from "@/lib/api";
import { MfaDeleteDialog } from "@/components/MfaDeleteDialog";

type SearchResult = { retrieval_audit_id: string; citations: Array<{ source_id: string; segment_id: string; source_name: string; source_version: number; text: string; score: number; vector_score?: number }> };
type Health = { state: string; active_sources: number; indexed_segments: number; capabilities?: string[]; pgvector_available?: boolean; vector_storage?: string; embedding_model?: string };
type ScrapeResponse = { discovered: number; created: number; skipped: number; failed: Array<{ video_id: string; error: string }>; provider_requested_at: string; trigger: string };
type YouTubeSchedule = { configured: boolean; enabled: boolean; run_at: string; timezone: string; weekdays: number[]; next_run_at: string | null; saved_at: string | null; query: string; limit: number; languages: string[]; category: string };
type YouTubeRun = Resource & { trigger: string; provider: string; provider_requested_at?: string; scheduled_at?: string; completed_at?: string; query: string; discovered?: number; created?: number; skipped?: number };
type AssistantAnswer = { status: string; answer: string; active_trade_warning?: string | null; citations: Array<{ document_id: string; segment_id: string; score: number; provenance: Record<string, string> }>; retrieval_audit_id: string };
type EmbeddingConfiguration = { configured: boolean; provider: string; connection_id: string | null; model: string; dimensions: number; verified_at: string | null; reindexed_segments?: number };

export function KnowledgeSources() {
  const client = useQueryClient();
  const sources = useQuery<Resource[]>({ queryKey: ["knowledge", "sources"], queryFn: () => api("/knowledge/sources") });
  const health = useQuery<Health>({ queryKey: ["knowledge", "health"], queryFn: () => api("/knowledge/health") });
  const youtubeSchedule = useQuery<YouTubeSchedule>({ queryKey: ["knowledge", "youtube", "schedule"], queryFn: () => api("/knowledge/youtube/schedule") });
  const youtubeRuns = useQuery<YouTubeRun[]>({ queryKey: ["knowledge", "youtube", "runs"], queryFn: () => api("/knowledge/youtube/runs"), refetchInterval: 30_000 });
  const connections = useQuery<Resource[]>({ queryKey: ["configuration", "connections"], queryFn: () => api("/configuration/connections") });
  const embeddingConfiguration = useQuery<EmbeddingConfiguration>({ queryKey: ["knowledge", "embedding-configuration"], queryFn: () => api("/knowledge/embedding-configuration") });
  const [source, setSource] = useState({ name: "", content: "", category: "general", tags: "" });
  const [file, setFile] = useState<File | null>(null);
  const [scrape, setScrape] = useState({ query: "trading strategy", limit: "5" });
  const [youtubeScheduleDraft, setYoutubeScheduleDraft] = useState<YouTubeSchedule | null>(null);
  const [youtubeScheduleEditing, setYoutubeScheduleEditing] = useState(false);
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchResult | null>(null);
  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState<AssistantAnswer | null>(null);
  const [message, setMessage] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<Resource | null>(null);
  const [embeddingDraft, setEmbeddingDraft] = useState<EmbeddingConfiguration | null>(null);
  const refresh = () => client.invalidateQueries({ queryKey: ["knowledge"] });
  const create = useMutation({
    mutationFn: () => api("/knowledge/sources", { method: "POST", body: JSON.stringify({ ...source, tags: source.tags.split(",").map(value => value.trim()).filter(Boolean) }) }),
    onSuccess: async () => { setSource({ name: "", content: "", category: "general", tags: "" }); setMessage("Source indexed with versioned chunks and vectors."); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const upload = useMutation({
    mutationFn: () => { if (!file) throw new Error("Choose a document or transcript file first"); const body = new FormData(); body.append("file", file); body.append("category", source.category); body.append("tags", source.tags); return api<Resource & { duplicate?: boolean }>("/knowledge/sources/upload", { method: "POST", body }); },
    onSuccess: async (item: Resource & { duplicate?: boolean }) => { setFile(null); setMessage(item.duplicate ? "That document was already indexed; no duplicate was created." : "Document extracted and indexed."); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const scrapeYoutube = useMutation({
    mutationFn: () => api<ScrapeResponse>("/knowledge/youtube/scrape", { method: "POST", body: JSON.stringify({ query: scrape.query, limit: Number(scrape.limit), languages: ["en"], category: "trading" }) }),
    onSuccess: async result => { setMessage(`SerpApi called ${new Date(result.provider_requested_at).toLocaleString()}: ${result.created} indexed, ${result.skipped} already known, ${result.failed.length} unavailable.`); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const act = useMutation({
    mutationFn: ({ id, action }: { id: string; action: "reprocess" | "disable" }) => api(`/knowledge/sources/${id}/${action}`, { method: "POST", body: action === "reprocess" ? JSON.stringify({ name: String(sources.data?.find(item => item.id === id)?.name ?? "Source"), content: source.content || "Reprocessed by operator", category: String(sources.data?.find(item => item.id === id)?.category ?? "general") }) : undefined }),
    onSuccess: refresh,
    onError: (error: Error) => setMessage(error.message),
  });
  const deleteSource = useMutation({
    mutationFn: (code: string) => { if (!deleteTarget) throw new Error("Choose a source to remove"); return withStepUp("knowledge.change", code, grant => api(`/knowledge/sources/${deleteTarget.id}`, { method: "DELETE", headers: { "Step-Up-Grant": grant } })); },
    onSuccess: async () => { setDeleteTarget(null); setMessage("Knowledge source removed; its audit history is retained."); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const search = useMutation({ mutationFn: () => api<SearchResult>("/knowledge/search", { method: "POST", body: JSON.stringify({ query, limit: 10 }) }), onSuccess: setResults, onError: (error: Error) => setMessage(error.message) });
  const ask = useMutation({ mutationFn: () => api<AssistantAnswer>("/knowledge/assistant", { method: "POST", body: JSON.stringify({ question, limit: 8 }) }), onSuccess: setAnswer, onError: (error: Error) => setMessage(error.message) });
  const editableYoutubeSchedule = youtubeScheduleDraft ?? youtubeSchedule.data;
  const saveYoutubeSchedule = useMutation({
    mutationFn: () => { if (!editableYoutubeSchedule) throw new Error("Schedule is still loading"); const { enabled, run_at, timezone, weekdays, query, limit, languages, category } = editableYoutubeSchedule; return api<YouTubeSchedule>("/knowledge/youtube/schedule", { method: "PUT", body: JSON.stringify({ enabled, run_at, timezone, weekdays, query, limit, languages, category }) }); },
    onSuccess: async result => { setYoutubeScheduleDraft(result); setYoutubeScheduleEditing(false); setMessage("YouTube discovery schedule saved. SerpApi calls will be recorded below."); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const removeYoutubeSchedule = useMutation({
    mutationFn: () => api<YouTubeSchedule>("/knowledge/youtube/schedule", { method: "DELETE" }),
    onSuccess: async result => { setYoutubeScheduleDraft(result); setYoutubeScheduleEditing(false); setMessage("YouTube discovery schedule removed. SerpApi will only be called manually."); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const changeYoutubeSchedule = (patch: Partial<YouTubeSchedule>) => { if (editableYoutubeSchedule) setYoutubeScheduleDraft({ ...editableYoutubeSchedule, ...patch }); };
  const editableEmbedding = embeddingDraft ?? embeddingConfiguration.data;
  const openAiConnections = (connections.data ?? []).filter(item => item.provider === "OPENAI" && item.state !== "DELETED");
  const saveEmbedding = useMutation({
    mutationFn: () => { if (!editableEmbedding?.connection_id) throw new Error("Select an OpenAI connection first"); return api<EmbeddingConfiguration>("/knowledge/embedding-configuration", { method: "PUT", body: JSON.stringify({ connection_id: editableEmbedding.connection_id, model: editableEmbedding.model, dimensions: editableEmbedding.dimensions }) }); },
    onSuccess: async result => { setEmbeddingDraft(result); setMessage(`OpenAI embeddings verified and saved. ${result.reindexed_segments ?? 0} existing segments were re-embedded.`); await refresh(); },
    onError: (error: Error) => setMessage(error.message),
  });
  const submit = (event: FormEvent) => { event.preventDefault(); setMessage(""); create.mutate(); };
  return <section className="section-stack">
    <header><p className="eyebrow">Context-only retrieval</p><h1>Knowledge sources</h1><p className="muted">Import documents, transcripts, and approved strategy artifacts. Indexed content remains context-only and is searchable with lexical plus vector scoring.</p></header>
    <div className="grid two">
      <form className="card form-stack" onSubmit={submit}><h2>Add text source</h2><label>Name<input required value={source.name} onChange={e => setSource({ ...source, name: e.target.value })} /></label><label>Category<input required value={source.category} onChange={e => setSource({ ...source, category: e.target.value })} /></label><label>Tags<input placeholder="playbook, forex" value={source.tags} onChange={e => setSource({ ...source, tags: e.target.value })} /></label><label>Content<textarea required rows={7} value={source.content} onChange={e => setSource({ ...source, content: e.target.value })} /></label><button className="btn primary" disabled={create.isPending}>Ingest and index</button></form>
      <div className="section-stack"><form className="card form-stack" onSubmit={e => { e.preventDefault(); upload.mutate(); }}><h2>Upload document or transcript</h2><p className="muted">PDF, DOCX, TXT, Markdown, VTT, and SRT up to 25 MB. Content hashes prevent duplicate ingestion.</p><input required type="file" accept=".pdf,.docx,.txt,.md,.vtt,.srt" onChange={e => setFile(e.target.files?.[0] ?? null)} /><label>Category<input value={source.category} onChange={e => setSource({ ...source, category: e.target.value })} /></label><label>Tags<input value={source.tags} onChange={e => setSource({ ...source, tags: e.target.value })} /></label><button className="btn" disabled={upload.isPending}>Upload and index</button></form><form className="card form-stack" onSubmit={e => { e.preventDefault(); scrapeYoutube.mutate(); }}><h2>YouTube trading knowledge</h2><p className="muted">Uses the configured SerpApi connection for discovery and youtube-transcript-api for captions. Previously indexed video IDs are skipped.</p><label>Search query<input required value={scrape.query} onChange={e => setScrape({ ...scrape, query: e.target.value })} /></label><label>Videos to inspect<input type="number" min="1" max="20" value={scrape.limit} onChange={e => setScrape({ ...scrape, limit: e.target.value })} /></label><button className="btn" disabled={scrapeYoutube.isPending}>Discover and ingest transcripts</button></form></div>
    </div>
    {message && <p className="notice">{message}</p>}
    <article className="card form-stack">
      <h2>YouTube discovery schedule and SerpApi calls</h2>
      <p className="muted">Each scheduled or manual provider call is timestamped. Successful transcripts are chunked and written to the owner-scoped knowledge index.</p>
      {editableYoutubeSchedule?.configured && !youtubeScheduleEditing ? <div className="inset form-stack"><strong>Saved YouTube schedule</strong><span>{editableYoutubeSchedule.enabled ? `${editableYoutubeSchedule.run_at} · ${editableYoutubeSchedule.timezone} · “${editableYoutubeSchedule.query}”` : "Disabled"}</span><small>Next SerpApi call: {editableYoutubeSchedule.next_run_at ? new Date(editableYoutubeSchedule.next_run_at).toLocaleString() : "Schedule disabled"}</small><div className="actions"><button className="btn" onClick={() => setYoutubeScheduleEditing(true)}>Edit / replace schedule</button><button className="btn danger" disabled={removeYoutubeSchedule.isPending} onClick={() => removeYoutubeSchedule.mutate()}>Remove schedule</button></div></div> : editableYoutubeSchedule ? <><div className="form-grid"><label>Search query<input value={editableYoutubeSchedule.query} onChange={event => changeYoutubeSchedule({ query: event.target.value })} /></label><label>Videos per call<input type="number" min="1" max="20" value={editableYoutubeSchedule.limit} onChange={event => changeYoutubeSchedule({ limit: Number(event.target.value) })} /></label><label>Run time<input type="time" value={editableYoutubeSchedule.run_at} onChange={event => changeYoutubeSchedule({ run_at: event.target.value })} /></label><label>Timezone<input value={editableYoutubeSchedule.timezone} onChange={event => changeYoutubeSchedule({ timezone: event.target.value })} /></label></div><label><input type="checkbox" checked={editableYoutubeSchedule.enabled} onChange={event => changeYoutubeSchedule({ enabled: event.target.checked })} /> Enable scheduled SerpApi discovery</label><fieldset><legend>Run on</legend><div className="actions">{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map((day, index) => <label key={day}><input type="checkbox" checked={editableYoutubeSchedule.weekdays.includes(index)} onChange={event => changeYoutubeSchedule({ weekdays: event.target.checked ? [...new Set([...editableYoutubeSchedule.weekdays, index])].sort() : editableYoutubeSchedule.weekdays.filter(value => value !== index) })} /> {day}</label>)}</div></fieldset><div className="actions"><button className="btn primary" disabled={saveYoutubeSchedule.isPending || !editableYoutubeSchedule.query || (editableYoutubeSchedule.enabled && !editableYoutubeSchedule.weekdays.length)} onClick={() => saveYoutubeSchedule.mutate()}>{saveYoutubeSchedule.isPending ? "Saving…" : editableYoutubeSchedule.configured ? "Replace YouTube schedule" : "Save YouTube schedule"}</button>{editableYoutubeSchedule.configured ? <button className="btn" onClick={() => { setYoutubeScheduleDraft(null); setYoutubeScheduleEditing(false); }}>Cancel</button> : null}</div></> : <p>Loading schedule…</p>}
      <h3>Recent SerpApi invocation history</h3>
      {youtubeRuns.data?.length ? <ul className="record-list">{youtubeRuns.data.map(run => <li key={run.id}><strong>{run.trigger} · {run.state}</strong><span>{run.query}</span><small>Provider called: {run.provider_requested_at ? new Date(run.provider_requested_at).toLocaleString() : run.scheduled_at ? `queued ${new Date(run.scheduled_at).toLocaleString()}` : "not called yet"} · indexed {run.created ?? 0} / discovered {run.discovered ?? 0}</small></li>)}</ul> : <p className="empty">No SerpApi calls recorded yet. Without a saved schedule, calls are manual only.</p>}
    </article>
    <article className="card form-stack"><h2>OpenAI knowledge embeddings</h2><p className="muted">The saved selection is the owner-scoped source of truth. Saving performs a live OpenAI embedding call and re-embeds existing knowledge; new documents and search queries then use the same model and dimensions.</p>{editableEmbedding ? <><label>OpenAI connection<select required value={editableEmbedding.connection_id ?? ""} onChange={event => setEmbeddingDraft({ ...editableEmbedding, connection_id: event.target.value })}><option value="">Select a tested OpenAI connection</option>{openAiConnections.map(item => <option key={item.id} value={item.id}>{String(item.name)} · {String(item.health ?? "UNTESTED")}</option>)}</select></label><div className="form-grid"><label>Embedding model<select value={editableEmbedding.model.startsWith("text-embedding") ? editableEmbedding.model : "text-embedding-3-small"} onChange={event => { const model = event.target.value; setEmbeddingDraft({ ...editableEmbedding, model, dimensions: model.endsWith("large") ? 3072 : 1536 }); }}><option value="text-embedding-3-small">text-embedding-3-small</option><option value="text-embedding-3-large">text-embedding-3-large</option></select></label><label>Dimensions<input type="number" min="64" max={editableEmbedding.model.endsWith("large") ? 3072 : 1536} value={editableEmbedding.dimensions > 64 ? editableEmbedding.dimensions : 1536} onChange={event => setEmbeddingDraft({ ...editableEmbedding, dimensions: Number(event.target.value) })} /></label></div><button className="btn primary" disabled={!editableEmbedding.connection_id || saveEmbedding.isPending} onClick={() => saveEmbedding.mutate()}>{saveEmbedding.isPending ? "Testing and re-embedding…" : editableEmbedding.configured ? "Test and replace embedding configuration" : "Test and save embedding configuration"}</button>{editableEmbedding.configured ? <small>Verified {editableEmbedding.verified_at ? new Date(editableEmbedding.verified_at).toLocaleString() : "—"} · {editableEmbedding.model} · {editableEmbedding.dimensions} dimensions</small> : null}</> : <p>Loading embedding configuration…</p>}{!openAiConnections.length ? <p className="notice warn">Create an OpenAI credential and connection on the Connections page first.</p> : null}</article>
    <article className="card"><h2>Index health</h2>{health.isPending ? <p>Checking…</p> : <><dl className="metric-list"><div><dt>State</dt><dd className={health.data?.state === "HEALTHY" ? "good" : "warn"}>{health.data?.state}</dd></div><div><dt>Active sources</dt><dd>{health.data?.active_sources ?? "—"}</dd></div><div><dt>Indexed segments</dt><dd>{health.data?.indexed_segments ?? "—"}</dd></div><div><dt>pgvector extension</dt><dd className={health.data?.pgvector_available ? "good" : "warn"}>{health.data?.pgvector_available ? "AVAILABLE" : "UNAVAILABLE"}</dd></div><div><dt>Current vector storage</dt><dd>{health.data?.vector_storage ?? "—"}</dd></div><div><dt>Embedding model</dt><dd>{health.data?.embedding_model ?? "—"}</dd></div><div><dt>Capabilities</dt><dd>{health.data?.capabilities?.join(", ") ?? "—"}</dd></div></dl><p className="muted">Current flow: extract text → split into deterministic chunks → use the UI-selected OpenAI embedding when configured (otherwise the local fallback) → store vectors with the source record → use the same embedding model for hybrid lexical and cosine retrieval. pgvector is installed; vector payloads are still stored in owner-scoped resource JSON in this deployment.</p></>}</article>
    <article className="card"><h2>Owner-scoped sources</h2>{sources.isPending ? <p>Loading…</p> : sources.data?.length ? <div className="table-wrap"><table><thead><tr><th>Source</th><th>Type</th><th>Category</th><th>Segments</th><th>State</th><th>Actions</th></tr></thead><tbody>{sources.data.map(item => <tr key={item.id}><td><strong>{String(item.name)}</strong><br /><small>v{String(item.generation)} · {String(item.content_hash).slice(0, 10)}</small></td><td>{String(item.source_kind ?? "DOCUMENT")}</td><td>{String(item.category)}</td><td>{String(item.segment_count)}</td><td>{item.state}</td><td><div className="actions"><button className="btn compact" disabled={act.isPending} onClick={() => act.mutate({ id: item.id, action: "reprocess" })}>Reprocess</button><button className="btn compact" disabled={act.isPending} onClick={() => act.mutate({ id: item.id, action: "disable" })}>Disable</button><button className="btn compact danger" disabled={act.isPending || deleteSource.isPending} onClick={() => setDeleteTarget(item)}>Delete</button></div></td></tr>)}</tbody></table></div> : <p className="empty">No knowledge sources yet.</p>}</article>
    {deleteTarget ? <MfaDeleteDialog key={deleteTarget.id} targetLabel={String(deleteTarget.name)} scope="knowledge.change" busy={deleteSource.isPending} error={deleteSource.error instanceof Error ? deleteSource.error.message : undefined} onCancel={() => setDeleteTarget(null)} onConfirm={code => deleteSource.mutate(code)} /> : null}
    <form className="card form-stack" onSubmit={e => { e.preventDefault(); search.mutate(); }}><h2>Audited hybrid search</h2><div className="actions"><input required placeholder="Search knowledge" value={query} onChange={e => setQuery(e.target.value)} /><button className="btn primary" disabled={search.isPending}>Search</button></div>{results && <><p className="muted">Retrieval audit {results.retrieval_audit_id.slice(0, 12)}</p>{results.citations.length ? <ol>{results.citations.map(item => <li key={item.segment_id}><p>{item.text}</p><small>{item.source_name} · source v{item.source_version} · score {item.score.toFixed(3)} · vector {item.vector_score?.toFixed(3) ?? "—"}</small></li>)}</ol> : <p className="empty">No matching authorized chunks.</p>}</>}</form>
    <form className="card form-stack" onSubmit={e => { e.preventDefault(); ask.mutate(); }}><h2>Knowledge Assistant</h2><p className="muted">Ask about indexed documents, transcripts, or live journal context. Answers are cited and cannot create trade commands. Refusal policy: execution requests are refused.</p><div className="actions"><input required placeholder="Ask an evidence question" value={question} onChange={e => setQuestion(e.target.value)} /><button className="btn primary" disabled={ask.isPending}>Ask</button></div>{answer && <><p className={answer.status === "ANSWERED" ? "good" : "warn"}>{answer.status}</p>{answer.active_trade_warning && <p className="notice warn">{answer.active_trade_warning}</p>}<pre>{answer.answer}</pre><small>Citations: {answer.citations.length} · Retrieval audit {answer.retrieval_audit_id.slice(0, 12)}</small></>}</form>
  </section>;
}
