"use client";

import { useState } from "react";

import type { StrategyVersionSummary } from "./StrategyVersions";

export type BacktestEvidence = { id: string; state: string; manifest_hash: string; execution_model_version: string; metrics: Record<string, string | number | string[] | null> };

export function ResearchBacktest({ selectedVersion, backtest, busy, jobId, onRunBacktest }: { selectedVersion?: StrategyVersionSummary; backtest?: BacktestEvidence; busy: boolean; jobId?: string; onRunBacktest: (manifestHash?: string) => Promise<void> }) {
  const [manifestHash, setManifestHash] = useState("");
  return <section aria-labelledby="research-backtest"><h3 id="research-backtest">Chronological backtest</h3><p>The run freezes the immutable definition, broker observations, execution assumptions, and conservative same-bar policy.</p><details><summary>Reproducibility controls</summary><label htmlFor="requested-manifest">Expected input manifest (optional)<input id="requested-manifest" minLength={8} onChange={(event) => setManifestHash(event.target.value)} placeholder="Previously recorded hash" value={manifestHash} /></label><small>Leave empty for a new manifest. Supplying a prior hash records the requested reproduction target.</small></details><button disabled={!selectedVersion || busy} onClick={() => onRunBacktest(manifestHash || undefined)} type="button">{busy ? "Running…" : "Run reproducible backtest"}</button>{jobId ? <p>Durable job <button className="text-button" onClick={() => window.dispatchEvent(new CustomEvent("traderx:workspace", { detail: "operations" }))} type="button">{jobId.slice(0, 8)}… · open controls</button></p> : null}{backtest ? <><dl className="evidence-metrics"><div><dt>State</dt><dd>{backtest.state}</dd></div><div><dt>Trades</dt><dd>{backtest.metrics.trades}</dd></div><div><dt>Net P/L</dt><dd>{backtest.metrics.net_pnl}</dd></div><div><dt>Average R</dt><dd>{backtest.metrics.average_r}</dd></div><div><dt>Maximum drawdown</dt><dd>{backtest.metrics.maximum_drawdown}</dd></div><div><dt>Execution model</dt><dd>{backtest.execution_model_version}</dd></div><div><dt>Total costs</dt><dd>{backtest.metrics.total_costs ?? "0"}</dd></div><div><dt>MAE / MFE</dt><dd>{backtest.metrics.maximum_mae ?? "0"} / {backtest.metrics.maximum_mfe ?? "0"}</dd></div></dl><details><summary>Frozen manifest and distributions</summary><p><strong>Manifest:</strong> <code>{backtest.manifest_hash}</code></p><p><strong>Equity curve:</strong> {Array.isArray(backtest.metrics.equity_curve) ? backtest.metrics.equity_curve.join(" → ") : "Unavailable"}</p><p><strong>R distribution:</strong> {Array.isArray(backtest.metrics.r_distribution) ? backtest.metrics.r_distribution.join(" · ") : "Unavailable"}</p></details></> : null}</section>;
}
