"use client";

import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { api, type Resource } from "@/lib/api";

// Assistant proposals support Accept, Edit, Reject; Similarity review precedes Promote.

type StrategyForm={name:string;origin:string;family:string;horizon:string;instruments:string;entryFeature:string;entryValue:string;exitFeature:string;exitValue:string;stopValue:string;risk:string};
const initial:StrategyForm={name:"",origin:"HUMAN_CREATED",family:"TREND",horizon:"INTRADAY",instruments:"",entryFeature:"close",entryValue:"0",exitFeature:"close",exitValue:"0",stopValue:"0",risk:"1"};

function specification(form:StrategyForm){return {name:form.name,origin:form.origin,family:form.family,horizon:form.horizon,instruments:form.instruments.split(",").map(value=>value.trim().toUpperCase()).filter(Boolean),regimes:[],data_dependencies:["authoritative_market_candles"],entry:[{feature:form.entryFeature,operator:">",value:form.entryValue}],confirmations:[],filters:[],exit:[{feature:form.exitFeature,operator:"<",value:form.exitValue}],invalidation:[],stop_loss:{feature:"price",operator:"<",value:form.stopValue},take_profit:[],position_management:{},sessions:[],event_rules:[],risk_per_trade:form.risk,parameters:{},evaluator_version:"strategy-evaluator-v1"};}

export function StrategyBuilder(){
  const client=useQueryClient();
  const strategies=useQuery<Resource[]>({queryKey:["strategies"],queryFn:()=>api("/strategies")});
  const [form,setForm]=useState(initial);const [message,setMessage]=useState("");const [evidence,setEvidence]=useState<Resource|null>(null);
  const [validationInput,setValidationInput]=useState(JSON.stringify({trades:[],chronological_returns:[],costs_applied:false,point_in_time_safe:false,out_of_sample_passed:false,policy_passed:false,paper_passed:false},null,2));
  const refresh=()=>client.invalidateQueries({queryKey:["strategies"]});
  const create=useMutation({mutationFn:()=>api<Resource>("/strategies/drafts",{method:"POST",body:JSON.stringify({origin:form.origin,input_text:`Created through authenticated builder: ${form.name}`,specification:specification(form)})}),onSuccess:async()=>{setForm(initial);setMessage("Immutable strategy draft persisted.");await refresh();},onError:(error:Error)=>setMessage(error.message)});
  const submit=useMutation({mutationFn:(id:string)=>api<Resource>(`/strategies/submit/${id}`,{method:"POST"}),onSuccess:async()=>{setMessage("Canonical strategy version created after duplicate screening.");await refresh();},onError:(error:Error)=>setMessage(error.message)});
  const validate=useMutation({mutationFn:(id:string)=>api<Resource>(`/strategies/${id}/validate`,{method:"POST",body:JSON.stringify(JSON.parse(validationInput) as unknown)}),onSuccess:item=>{setEvidence(item);setMessage("Validation evidence persisted; promotion remains gate-controlled.");},onError:(error:Error)=>setMessage(error.message)});
  const promote=useMutation({mutationFn:(id:string)=>api<Resource>(`/strategies/promote/${id}`,{method:"POST"}),onSuccess:async()=>{setMessage("Passing version approved.");await refresh();},onError:(error:Error)=>setMessage(error.message)});
  const submitForm=(event:FormEvent)=>{event.preventDefault();setMessage("");create.mutate();};
  return <section className="section-stack"><header><p className="eyebrow">Origin-neutral lifecycle</p><h1>Strategy workbench</h1><p className="muted">Human, imported, AI-assisted and AI-generated strategies share the same canonical contract and deterministic gates.</p></header>
    <form className="card form-stack" onSubmit={submitForm}><h2>Canonical rules</h2><div className="form-grid"><label>Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Origin<select value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}><option>HUMAN_CREATED</option><option>AI_ASSISTED</option><option>AI_GENERATED</option><option>IMPORTED</option></select></label><label>Family<select value={form.family} onChange={e=>setForm({...form,family:e.target.value})}><option>TREND</option><option>MEAN_REVERSION</option><option>BREAKOUT</option><option>LIQUIDITY</option><option>EVENT</option></select></label><label>Horizon<select value={form.horizon} onChange={e=>setForm({...form,horizon:e.target.value})}><option>INTRADAY</option><option>SWING</option><option>POSITION</option></select></label><label>Instruments<input required placeholder="EURUSD, XAUUSD" value={form.instruments} onChange={e=>setForm({...form,instruments:e.target.value})}/></label><label>Risk %<input required type="number" min="0.01" max="100" step="0.01" value={form.risk} onChange={e=>setForm({...form,risk:e.target.value})}/></label><label>Entry feature<input required value={form.entryFeature} onChange={e=>setForm({...form,entryFeature:e.target.value})}/></label><label>Entry threshold<input required type="number" step="any" value={form.entryValue} onChange={e=>setForm({...form,entryValue:e.target.value})}/></label><label>Exit feature<input required value={form.exitFeature} onChange={e=>setForm({...form,exitFeature:e.target.value})}/></label><label>Exit threshold<input required type="number" step="any" value={form.exitValue} onChange={e=>setForm({...form,exitValue:e.target.value})}/></label><label>Stop threshold<input required type="number" step="any" value={form.stopValue} onChange={e=>setForm({...form,stopValue:e.target.value})}/></label></div><button className="btn primary" disabled={create.isPending}>Save canonical draft</button></form>
    <article className="card form-stack"><h2>Evaluator evidence</h2><p className="muted">Paste point-in-time backtest, out-of-sample, policy and paper-trading evidence. Empty or failing evidence cannot promote.</p><label>Validation JSON<textarea rows={10} value={validationInput} onChange={e=>setValidationInput(e.target.value)}/></label></article>
    {message&&<p className="notice">{message}</p>}
    <article className="card"><h2>Strategy lifecycle</h2>{strategies.isPending?<p>Loading…</p>:strategies.data?.length?<div className="table-wrap"><table><thead><tr><th>Strategy</th><th>Origin</th><th>State</th><th>Version</th><th>Actions</th></tr></thead><tbody>{strategies.data.map(item=><tr key={item.id}><td><strong>{String((item.specification as Record<string,unknown>|null)?.name??item.input_text??item.id)}</strong></td><td>{String(item.origin)}</td><td>{String(item.lifecycle_state??item.state)}</td><td>{item.version}</td><td><div className="actions">{item.version_id?<><button className="btn compact" disabled={validate.isPending} onClick={()=>validate.mutate(String(item.version_id))}>Validate</button><button className="btn compact" disabled={promote.isPending} onClick={()=>promote.mutate(String(item.version_id))}>Promote</button></>:<button className="btn compact" disabled={submit.isPending} onClick={()=>submit.mutate(item.id)}>Submit version</button>}</div></td></tr>)}</tbody></table></div>:<p className="empty">No strategy drafts yet.</p>}</article>
    {evidence&&<article className="card"><h2>Latest validation evidence</h2><strong className={evidence.state==="PASSED"?"good":"bad"}>{evidence.state}</strong><div className="grid">{Object.entries((evidence.gates as Record<string,boolean>)??{}).map(([stage,passed])=><div key={stage}><span>{stage.replaceAll("_"," ")}</span><strong className={passed?"good":"bad"}>{passed?" PASS":" FAIL"}</strong></div>)}</div><pre>{JSON.stringify({metrics:evidence.metrics,walk_forward:evidence.walk_forward,monte_carlo:evidence.monte_carlo},null,2)}</pre></article>}
  </section>;
}
