export type PaperRunEvidence = { id: string; strategy_version_id: string; validation_run_id: string; state: string; metrics: Record<string, string | number>; criteria: { eligible: boolean; reason_codes: string[]; minimum_trades: number; minimum_duration_days: number }; comparison?: { divergence: string; disposition: string }; history: Array<{ id: string; direction: string; entry: string; exit?: string; pnl: string }> };
type Version = { id: string; sequence: number; lifecycle: string };
type Strategy = { id: string; name: string; versions: Version[] };
type Validation = { id: string; manifest_hash: string; state: string };

export function PaperTrading({ strategies, eligibleValidations, runs, selectedVersionId, selectedValidationId, selectedRunId, busy, onSelectVersion, onSelectValidation, onSelectRun, onRun }: { strategies: Strategy[]; eligibleValidations: Validation[]; runs: PaperRunEvidence[]; selectedVersionId: string; selectedValidationId: string; selectedRunId: string; busy: boolean; onSelectVersion: (id: string) => void; onSelectValidation: (id: string) => void; onSelectRun: (id: string) => void; onRun: () => Promise<void> }) {
  const versions = strategies.flatMap((strategy) => strategy.versions.map((version) => ({ ...version, strategyName: strategy.name }))).filter((version) => ["BACKTEST_PASSED", "PAPER_TRADING", "AWAITING_APPROVAL", "LIVE_APPROVED"].includes(version.lifecycle));
  const selected = runs.find((run) => run.id === selectedRunId);
  return <section aria-labelledby="paper-trading"><h3 id="paper-trading">Current-data paper evaluation</h3><p>Simulated fills use the same conservative execution model as backtesting. Nothing here can submit a broker order.</p>
    <div className="control-row"><label>Validated strategy version<select onChange={(event) => onSelectVersion(event.target.value)} value={selectedVersionId}><option value="">Select a version</option>{versions.map((version) => <option key={version.id} value={version.id}>{version.strategyName} · v{version.sequence} · {version.lifecycle}</option>)}</select></label><label>Passing validation<select onChange={(event) => onSelectValidation(event.target.value)} value={selectedValidationId}><option value="">Latest passing evidence</option>{eligibleValidations.map((validation) => <option key={validation.id} value={validation.id}>{validation.id.slice(0, 8)} · {validation.state}</option>)}</select></label><button disabled={busy || !selectedVersionId || eligibleValidations.length === 0} onClick={onRun} type="button">{busy ? "Evaluating…" : "Run paper evaluation"}</button></div>
    {eligibleValidations.length === 0 && selectedVersionId ? <p className="workspace-notice">This version has no passing validation evidence. Return to Strategies first.</p> : null}
    {runs.length ? <label>Paper run<select onChange={(event) => onSelectRun(event.target.value)} value={selectedRunId}>{runs.map((run) => <option key={run.id} value={run.id}>{run.id.slice(0, 8)} · {run.state}</option>)}</select></label> : <p className="workspace-notice">No paper evaluation has been run yet.</p>}
    {selected ? <><dl className="evidence-metrics"><div><dt>Disposition</dt><dd>{selected.state}</dd></div><div><dt>Trades</dt><dd>{selected.metrics.trades} / {selected.criteria.minimum_trades}</dd></div><div><dt>Duration</dt><dd>{selected.metrics.duration_days} / {selected.criteria.minimum_duration_days} days</dd></div><div><dt>Paper expectancy</dt><dd>{selected.metrics.paper_expectancy}</dd></div><div><dt>Net simulated P&amp;L</dt><dd>{selected.metrics.net_pnl}</dd></div><div><dt>Divergence</dt><dd>{selected.comparison?.divergence ?? "—"}</dd></div></dl>{selected.criteria.reason_codes.length ? <ul>{selected.criteria.reason_codes.map((reason) => <li key={reason}>{reason.replaceAll("_", " ")}</li>)}</ul> : <p className="status-message" data-tone="success">All paper evidence thresholds passed. Human approval is still required.</p>}</> : null}
  </section>;
}
