from __future__ import annotations

import hashlib
import json
import pprint
from dataclasses import dataclass
from decimal import Decimal

from packages.strategy_sdk.schema import StrategySpecification

OPS = {
    ">": lambda a, b: a > b,
    ">=": lambda a, b: a >= b,
    "<": lambda a, b: a < b,
    "<=": lambda a, b: a <= b,
    "==": lambda a, b: a == b,
}


@dataclass(frozen=True)
class CompiledStrategy:
    artifact_hash: str
    specification: StrategySpecification
    generated_code: str

    def evaluate(self, features: dict[str, Decimal]) -> bool:
        for rule in self.specification.entry:
            if rule.operator not in OPS or rule.feature not in features:
                return False
            right = features.get(str(rule.value), rule.value)
            right = Decimal(str(right))
            if not OPS[rule.operator](features[rule.feature], right):
                return False
        return True


def compile_strategy(spec: StrategySpecification) -> CompiledStrategy:
    payload = json.dumps(spec.model_dump(mode="json"), sort_keys=True).encode()
    return CompiledStrategy(
        hashlib.sha256(payload).hexdigest(),
        spec,
        render_strategy_code(spec),
    )


def render_strategy_code(spec: StrategySpecification) -> str:
    """Render the approved specification as deterministic, inspectable source code.

    The generated source is deliberately a small evaluator rather than an order
    executor.  It gives operators a reproducible implementation artifact to
    review while preserving Matrades' manual-execution boundary.
    """

    encoded = pprint.pformat(spec.model_dump(mode="json"), sort_dicts=True, width=100)
    return f'''"""Generated by Matrades; review before using in another system.
This module evaluates signals only. It never submits broker orders.
"""

from decimal import Decimal

SPECIFICATION = {encoded}

_OPERATORS = {{
    ">": lambda left, right: left > right,
    ">=": lambda left, right: left >= right,
    "<": lambda left, right: left < right,
    "<=": lambda left, right: left <= right,
    "==": lambda left, right: left == right,
}}


def _condition_matches(condition: dict, features: dict[str, Decimal]) -> bool:
    operator = condition.get("operator")
    if operator not in _OPERATORS:
        return False  # crossover conditions require a time series, not a snapshot
    feature = condition.get("feature")
    if feature not in features:
        return False
    right = condition.get("value")
    try:
        right_value = Decimal(str(features.get(str(right), right)))
        return bool(_OPERATORS[operator](Decimal(str(features[feature])), right_value))
    except (ArithmeticError, TypeError, ValueError):
        return False


def signal(features: dict[str, Decimal]) -> bool:
    """Return whether every entry condition is satisfied for this snapshot."""
    return all(_condition_matches(condition, features)
               for condition in SPECIFICATION["entry"])
'''
